#define WIND_SPEED 8.0
#define WIND_WAVES_LENGTH 0.25
#define WIND_WAVES_AMPLITUDE 0.03125
#define WIND_IMPULSES_SPEED 1.0
#define WIND_IMPULSE_CUT 4.0 // higher number - shorter impulse
#define RAIN_WIND_AMPLITUDE_BOOST 1.0
#define RAIN_WIND_SPEED_BOOST 2.0