#define HORIZONTAL_FOG_SHARPNESS 4.0
#define HORIZONTAL_FOG_HEIGHT 8.0
#define HORIZONTAL_FOG_MAX 0.5
#define BLUE_FOG_TINT vec3(0.25,0.35,1.0)
#define BLUE_FOG_START 1.0
#define UNDERWATER_FOG_MIN 0.35