//                                    !!!WARNING!!!
// Please do not edit this file! Instead, create a configuration pack using the template here: [TBD]

vec3 clearSkyColor = pow(FOG_COLOR.rgb, vec3(0.8));
vec3 clearSkyZenithColor = vec3(0.1, 0.2, 0.8) * length(clearSkyColor);
vec3 rainSkyColor = vec3(0.6, 0.6, 0.6) * length(FOG_COLOR.rgb);

float skyAttenuation = 1.0;
float skyZenithEdgeOffset = 1.5; // The height that the gradient near the horizon begins at (going down)