//                                    !!!WARNING!!!
// Please do not edit this file! Instead, create a configuration pack using the template here: [TBD]

float sunHaloIntensity = 0.6;
float moonHaloIntensity = 0.4;
float sunVisSize = 1.0;